### PR TITLE
Lindat auth fix

### PR DESCRIPTION
**Pull request by kosarko**
@tomachalek This was meant to be just a fix for the lindat_auth plugin (I guess the change there is needed due to the cheetah/jinja switch, or maybe it was not working even longer) there are few other (lindat related) commits, hope it's not too much of a mess.

### CODE REVIEW

**Comment by tomachalek** [comment]
I'am going to look at this tomorrow. We're in the middle of some client-side refactoring (almost done, resolving bugs) but I believe I will be able to merge this.

**Comment by kosarko** [comment]
No need to hurry. I'm not sure why it shows those conflicting files, yet there are just 3 changed files shown at the top. So if it seems as too much trouble, let me know, I guess I can cherry-pick the change or something.

**Comment by tomachalek** [comment]
I am not sure whether I've used the best way possible to merge this but it should be done by now. Please see the log `f603d6428b0effcd76c89a2e154ffde9679f6b68..360b1b6f76fae842ff1442393f1d94bc96f62fc7` and the actual changes and let me know. Thanks.

**Comment by kosarko** [comment]
looks good, thanks. Closing.

**Pull request closed without merging**
